export const bibleBooks = [
  { name: "Genesis", chapters: 50, id: "GEN" },
  { name: "Exodus", chapters: 40, id: "EXO" },
  { name: "Leviticus", chapters: 27, id: "LEV" },
  { name: "Numbers", chapters: 36, id: "NUM" },
  { name: "Deuteronomy", chapters: 34, id: "DEU" },
  { name: "Joshua", chapters: 24, id: "JOS" },
  { name: "Judges", chapters: 21, id: "JDG" },
  { name: "Ruth", chapters: 4, id: "RUT" },
  { name: "1 Samuel", chapters: 31, id: "1SA" },
  { name: "2 Samuel", chapters: 24, id: "2SA" },
  { name: "1 Kings", chapters: 22, id: "1KI" },
  { name: "2 Kings", chapters: 25, id: "2KI" },
  { name: "1 Chronicles", chapters: 29, id: "1CH" },
  { name: "2 Chronicles", chapters: 36, id: "2CH" },
  { name: "Ezra", chapters: 10, id: "EZR" },
  { name: "Nehemiah", chapters: 13, id: "NEH" },
  { name: "Esther", chapters: 10, id: "EST" },
  { name: "Job", chapters: 42, id: "JOB" },
  { name: "Psalms", chapters: 150, id: "PSA" },
  { name: "Proverbs", chapters: 31, id: "PRO" },
  { name: "Ecclesiastes", chapters: 12, id: "ECC" },
  { name: "Song of Solomon", chapters: 8, id: "SNG" },
  { name: "Isaiah", chapters: 66, id: "ISA" },
  { name: "Jeremiah", chapters: 52, id: "JER" },
  { name: "Lamentations", chapters: 5, id: "LAM" },
  { name: "Ezekiel", chapters: 48, id: "EZK" },
  { name: "Daniel", chapters: 12, id: "DAN" },
  { name: "Hosea", chapters: 14, id: "HOS" },
  { name: "Joel", chapters: 3, id: "JOL" },
  { name: "Amos", chapters: 9, id: "AMO" },
  { name: "Obadiah", chapters: 1, id: "OBA" },
  { name: "Jonah", chapters: 4, id: "JON" },
  { name: "Micah", chapters: 7, id: "MIC" },
  { name: "Nahum", chapters: 3, id: "NAM" },
  { name: "Habakkuk", chapters: 3, id: "HAB" },
  { name: "Zephaniah", chapters: 3, id: "ZEP" },
  { name: "Haggai", chapters: 2, id: "HAG" },
  { name: "Zechariah", chapters: 14, id: "ZEC" },
  { name: "Malachi", chapters: 4, id: "MAL" },
  { name: "Matthew", chapters: 28, id: "MAT" },
  { name: "Mark", chapters: 16, id: "MRK" },
  { name: "Luke", chapters: 24, id: "LUK" },
  { name: "John", chapters: 21, id: "JHN" },
  { name: "Acts", chapters: 28, id: "ACT" },
  { name: "Romans", chapters: 16, id: "ROM" },
  { name: "1 Corinthians", chapters: 16, id: "1CO" },
  { name: "2 Corinthians", chapters: 13, id: "2CO" },
  { name: "Galatians", chapters: 6, id: "GAL" },
  { name: "Ephesians", chapters: 6, id: "EPH" },
  { name: "Philippians", chapters: 4, id: "PHP" },
  { name: "Colossians", chapters: 4, id: "COL" },
  { name: "1 Thessalonians", chapters: 5, id: "1TH" },
  { name: "2 Thessalonians", chapters: 3, id: "2TH" },
  { name: "1 Timothy", chapters: 6, id: "1TI" },
  { name: "2 Timothy", chapters: 4, id: "2TI" },
  { name: "Titus", chapters: 3, id: "TIT" },
  { name: "Philemon", chapters: 1, id: "PHM" },
  { name: "Hebrews", chapters: 13, id: "HEB" },
  { name: "James", chapters: 5, id: "JAS" },
  { name: "1 Peter", chapters: 5, id: "1PE" },
  { name: "2 Peter", chapters: 3, id: "2PE" },
  { name: "1 John", chapters: 5, id: "1JN" },
  { name: "2 John", chapters: 1, id: "2JN" },
  { name: "3 John", chapters: 1, id: "3JN" },
  { name: "Jude", chapters: 1, id: "JUD" },
  { name: "Revelation", chapters: 22, id: "REV" },
];

export const bibleBookMapEnToZh = {
  "Genesis": "创世记",
  "Exodus": "出埃及记",
  "Leviticus": "利未记",
  "Numbers": "民数记",
  "Deuteronomy": "申命记",
  "Joshua": "约书亚记",
  "Judges": "士师记",
  "Ruth": "路得记",
  "1 Samuel": "撒母耳记上",
  "2 Samuel": "撒母耳记下",
  "1 Kings": "列王纪上",
  "2 Kings": "列王纪下",
  "1 Chronicles": "历代志上",
  "2 Chronicles": "历代志下",
  "Ezra": "以斯拉记",
  "Nehemiah": "尼希米记",
  "Esther": "以斯帖记",
  "Job": "约伯记",
  "Psalms": "诗篇",
  "Proverbs": "箴言",
  "Ecclesiastes": "传道书",
  "Song of Solomon": "雅歌",
  "Isaiah": "以赛亚书",
  "Jeremiah": "耶利米书",
  "Lamentations": "耶利米哀歌",
  "Ezekiel": "以西结书",
  "Daniel": "但以理书",
  "Hosea": "何西阿书",
  "Joel": "约珥书",
  "Amos": "阿摩司书",
  "Obadiah": "俄巴底亚书",
  "Jonah": "约拿书",
  "Micah": "弥迦书",
  "Nahum": "那鸿书",
  "Habakkuk": "哈巴谷书",
  "Zephaniah": "西番雅书",
  "Haggai": "哈该书",
  "Zechariah": "撒迦利亚书",
  "Malachi": "玛拉基书",
  "Matthew": "马太福音",
  "Mark": "马可福音",
  "Luke": "路加福音",
  "John": "约翰福音",
  "Acts": "使徒行传",
  "Romans": "罗马书",
  "1 Corinthians": "哥林多前书",
  "2 Corinthians": "哥林多后书",
  "Galatians": "加拉太书",
  "Ephesians": "以弗所书",
  "Philippians": "腓立比书",
  "Colossians": "歌罗西书",
  "1 Thessalonians": "帖撒罗尼迦前书",
  "2 Thessalonians": "帖撒罗尼迦后书",
  "1 Timothy": "提摩太前书",
  "2 Timothy": "提摩太后书",
  "Titus": "提多书",
  "Philemon": "腓利门书",
  "Hebrews": "希伯来书",
  "James": "雅各书",
  "1 Peter": "彼得前书",
  "2 Peter": "彼得后书",
  "1 John": "约翰一书",
  "2 John": "约翰二书",
  "3 John": "约翰三书",
  "Jude": "犹大书",
  "Revelation": "启示录",
};

export const bibleBookMapEnToZhTraditional = {
  "Genesis": "創世記",
  "Exodus": "出埃及記",
  "Leviticus": "利未記",
  "Numbers": "民數記",
  "Deuteronomy": "申命記",
  "Joshua": "約書亞記",
  "Judges": "士師記",
  "Ruth": "路得記",
  "1 Samuel": "撒母耳記上",
  "2 Samuel": "撒母耳記下",
  "1 Kings": "列王紀上",
  "2 Kings": "列王紀下",
  "1 Chronicles": "歷代志上",
  "2 Chronicles": "歷代志下",
  "Ezra": "以斯拉記",
  "Nehemiah": "尼希米記",
  "Esther": "以斯帖記",
  "Job": "約伯記",
  "Psalms": "詩篇",
  "Proverbs": "箴言",
  "Ecclesiastes": "傳道書",
  "Song of Solomon": "雅歌",
  "Isaiah": "以賽亞書",
  "Jeremiah": "耶利米書",
  "Lamentations": "耶利米哀歌",
  "Ezekiel": "以西結書",
  "Daniel": "但以理書",
  "Hosea": "何西阿書",
  "Joel": "約珥書",
  "Amos": "阿摩司書",
  "Obadiah": "俄巴底亞書",
  "Jonah": "約拿書",
  "Micah": "彌迦書",
  "Nahum": "那鴻書",
  "Habakkuk": "哈巴谷書",
  "Zephaniah": "西番雅書",
  "Haggai": "哈該書",
  "Zechariah": "撒迦利亞書",
  "Malachi": "瑪拉基書",
  "Matthew": "馬太福音",
  "Mark": "馬可福音",
  "Luke": "路加福音",
  "John": "約翰福音",
  "Acts": "使徒行傳",
  "Romans": "羅馬書",
  "1 Corinthians": "哥林多前書",
  "2 Corinthians": "哥林多後書",
  "Galatians": "加拉太書",
  "Ephesians": "以弗所書",
  "Philippians": "腓立比書",
  "Colossians": "歌羅西書",
  "1 Thessalonians": "帖撒羅尼迦前書",
  "2 Thessalonians": "帖撒羅尼迦後書",
  "1 Timothy": "提摩太前書",
  "2 Timothy": "提摩太後書",
  "Titus": "提多書",
  "Philemon": "腓利門書",
  "Hebrews": "希伯來書",
  "James": "雅各書",
  "1 Peter": "彼得前書",
  "2 Peter": "彼得後書",
  "1 John": "約翰一書",
  "2 John": "約翰二書",
  "3 John": "約翰三書",
  "Jude": "猶大書",
  "Revelation": "啟示錄",
};
