export const bibleBooks = [
  { name: "Genesis", chapters: 50, id: "GEN" },
  { name: "Exodus", chapters: 40, id: "EXO" },
  { name: "Leviticus", chapters: 27, id: "LEV" },
  { name: "Numbers", chapters: 36, id: "NUM" },
  { name: "Deuteronomy", chapters: 34, id: "DEU" },
  { name: "Joshua", chapters: 24, id: "JOS" },
  { name: "Judges", chapters: 21, id: "JDG" },
  { name: "Ruth", chapters: 4, id: "RUT" },
  { name: "1 Samuel", chapters: 31, id: "1SA" },
  { name: "2 Samuel", chapters: 24, id: "2SA" },
  { name: "1 Kings", chapters: 22, id: "1KI" },
  { name: "2 Kings", chapters: 25, id: "2KI" },
  { name: "1 Chronicles", chapters: 29, id: "1CH" },
  { name: "2 Chronicles", chapters: 36, id: "2CH" },
  { name: "Ezra", chapters: 10, id: "EZR" },
  { name: "Nehemiah", chapters: 13, id: "NEH" },
  { name: "Esther", chapters: 10, id: "EST" },
  { name: "Job", chapters: 42, id: "JOB" },
  { name: "Psalms", chapters: 150, id: "PSA" },
  { name: "Proverbs", chapters: 31, id: "PRO" },
  { name: "Ecclesiastes", chapters: 12, id: "ECC" },
  { name: "Song of Solomon", chapters: 8, id: "SNG" },
  { name: "Isaiah", chapters: 66, id: "ISA" },
  { name: "Jeremiah", chapters: 52, id: "JER" },
  { name: "Lamentations", chapters: 5, id: "LAM" },
  { name: "Ezekiel", chapters: 48, id: "EZK" },
  { name: "Daniel", chapters: 12, id: "DAN" },
  { name: "Hosea", chapters: 14, id: "HOS" },
  { name: "Joel", chapters: 3, id: "JOL" },
  { name: "Amos", chapters: 9, id: "AMO" },
  { name: "Obadiah", chapters: 1, id: "OBA" },
  { name: "Jonah", chapters: 4, id: "JON" },
  { name: "Micah", chapters: 7, id: "MIC" },
  { name: "Nahum", chapters: 3, id: "NAM" },
  { name: "Habakkuk", chapters: 3, id: "HAB" },
  { name: "Zephaniah", chapters: 3, id: "ZEP" },
  { name: "Haggai", chapters: 2, id: "HAG" },
  { name: "Zechariah", chapters: 14, id: "ZEC" },
  { name: "Malachi", chapters: 4, id: "MAL" },
  { name: "Matthew", chapters: 28, id: "MAT" },
  { name: "Mark", chapters: 16, id: "MRK" },
  { name: "Luke", chapters: 24, id: "LUK" },
  { name: "John", chapters: 21, id: "JHN" },
  { name: "Acts", chapters: 28, id: "ACT" },
  { name: "Romans", chapters: 16, id: "ROM" },
  { name: "1 Corinthians", chapters: 16, id: "1CO" },
  { name: "2 Corinthians", chapters: 13, id: "2CO" },
  { name: "Galatians", chapters: 6, id: "GAL" },
  { name: "Ephesians", chapters: 6, id: "EPH" },
  { name: "Philippians", chapters: 4, id: "PHP" },
  { name: "Colossians", chapters: 4, id: "COL" },
  { name: "1 Thessalonians", chapters: 5, id: "1TH" },
  { name: "2 Thessalonians", chapters: 3, id: "2TH" },
  { name: "1 Timothy", chapters: 6, id: "1TI" },
  { name: "2 Timothy", chapters: 4, id: "2TI" },
  { name: "Titus", chapters: 3, id: "TIT" },
  { name: "Philemon", chapters: 1, id: "PHM" },
  { name: "Hebrews", chapters: 13, id: "HEB" },
  { name: "James", chapters: 5, id: "JAS" },
  { name: "1 Peter", chapters: 5, id: "1PE" },
  { name: "2 Peter", chapters: 3, id: "2PE" },
  { name: "1 John", chapters: 5, id: "1JN" },
  { name: "2 John", chapters: 1, id: "2JN" },
  { name: "3 John", chapters: 1, id: "3JN" },
  { name: "Jude", chapters: 1, id: "JUD" },
  { name: "Revelation", chapters: 22, id: "REV" },
];
